version: "3.7"
services:
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    environment:
      - DEBUG=1
    networks:
      - sonar_network

networks:
  sonar_network:
    external: true
